### ISSUE TITLE
Ménage d'autonme

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1111]
- [x] Change the code header to follow the Lab-STICC one,
- [x] Create a deb repo for OrbisGIS. See #989
- [x] Updates all the OrbisGIS plugins to be compatible with the version 5.1.0
- [x] Rename orbisgis-plugin_views by orbisgis-official-plugin (update jenkins jobs and nexus push)
- [x] replace https://www.transifex.com/irstv/teams/1247/fr/ by orbisgis team
- [x] Improve javadoc for all methods and classes,
- [x] Document the development process (versions, builds, plugin dependencies with the core...) A good example is available here http://docs.renjin.org/en/latest/introduction.html#about-renjin
- [x] Create stable and unstable versions and synchronize them with jenkins,
- [x] Document and clarify the OSGI architecture
- [x] Document and clarify the Layer and data models (RowSet, DB Triggers...)
- [ ] Rename GeoStream by WMSLayer and clarify all WMS API
- [x] Clarify `<artifactId>orbisgis-nexus</artifactId> <version>1</version>`

**Comment by ebocher** [comment]
- [ ] Updates all the OrbisGIS plugins to be compatible with the version 5.1.0

**Comment by ebocher** [comment]
- [ ] Document and clarify the Layer and data models (RowSet, DB Triggers...)

**Comment by ebocher** [comment]
- [ ] Rename orbisgis-plugin_views by orbisgis-official-plugin (update jenkins jobs and nexus push)

**Comment by ebocher** [comment]
- [ ] Rename GeoStream by WMSLayer and clarify all WMS API

**Comment by ebocher** [comment]
[ ] replace https://www.transifex.com/irstv/teams/1247/fr/ by orbisgis team

**Comment by ebocher** [comment]
- [ ] Clarify ```<artifactId>orbisgis-nexus</artifactId> <version>1</version>```

**Comment by gpetit** [comment]
Concerning Transifex. The IRSTV organisation has been renamed by OrbisGIS. So we now have the same structure as on GitHub.
The translation of the OrbisGIS software is available at the following adress https://www.transifex.com/orbisgis/orbisgis/
and the team is here : https://www.transifex.com/orbisgis/teams/

Since on the official website and on the wiki the url are http://www.transifex.com/projects/p/orbisgis/, it seems that Transifex is able to make a redirection to https://www.transifex.com/orbisgis/orbisgis/ ... so in theroy we don't have anything to update.

@SPalominos @nicolas-f maybe we should just check if the "translation chain" with .po files is still working ?

**Comment by nicolas-f** [comment]
It seems that the transifex configuration has not been updated with new plugins:

https://github.com/orbisgis/orbisgis/blob/master/.tx/config

The guide is here 

https://github.com/orbisgis/orbisgis/wiki/6.-Transifex-translation

**Comment by SPalominos** [comment]
Thanks @nicolas-f, ill open a separated issue for that.
