### ISSUE TITLE
WPS refresh list of tables on PostGIS database

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1197]
The list of tables is not updated when the content of the data change.

To test 

Import a shapefile with a WPS script
Try to export the new table (imported shape) with a WPS script. The table is not listed in the @JDBCTableInput.

Note : The user must refresh the geocatalog to display the new table.

Maybe @nicolas-f could comment this issue.

**Comment by ebocher** [comment]
It seems there is two possibilities
- add a timer to refresh datamanager
- add button in the UI to refresh the list of tables

@nicolas-f

**Comment by SPalominos** [comment]
To complete the previous comment, now the WPS client updates the table list exactly in the same way as the geocatalog.
There is two other possibilities but them don't seem to be good ideas (in my opinion) :
- Refresh the list on opening a script : The user can't use a table add after the script has been open, he has to close and reopen it.
- Refresh the list on clicking on the UI components : It can't be done on click because the JComponent will be frozen and modified and it causes wrong behaviours. It should be done on entering the mouse in the component (same way as the JDBCTableField) but the refresh would be done quite often.

**Comment by gpetit** [comment]
Just to complete, for me it's normal that the list is not refreshed if the WPS is already open.
If you create a new layer, you have to reopen the WPS script panel to see the layer in the list.

**Comment by ebocher** [comment]
As discussed with @SPalominos we decide to get the list of tables when the script is loaded

**Comment by ebocher** [comment]
thanks
