### ISSUE TITLE
Sort action on table editor too slow

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#997]
The sort action on the table editor is unmanageable.
A sort action on a postgresql table  (44 000 rows) on a server side takes more than 5 minutes to create the cache of PK  values.... By the way the process cannot be stopped.

**Comment by SPalominos** [comment]
Postponed  to 5.2

**Comment by ebocher** [comment]
Critical for 5.1

**Comment by SPalominos** [comment]
I'm on it.

**Comment by SPalominos** [comment]
Just to check if I have understood well the sorting behaviour, these are the main steps :
 - The user select the column to be sorted.
 - If there is a PK :
   - A map linking the PK and the rowId is created
   - A RowSet is get from the SQL request `SELECT pk FROM table ORDER BY ascordesc` (the sorting is done server side)
   - The iteration on the RowSet is done with the linking map to get the new order of the rowId
   - The new rowId order is returned
 - If there is no PK :
   - A map linking the rowId and the sorted column values is created.
   - The map is sorted by the column values (the sorting is done client side)
   - The new rowId order is returned

Pros of this method : we keep the link between the non-sorted rowId and the new one so we can keep the used selection for example.
Cons of this method : the sort take a long time because to get the new rowId order, a whole column should be read from the RowSet (the PK column or the sorted column).

@nicolas-f @ebocher What do you think? Any suggestion ?

**Comment by nicolas-f** [comment]
Yes it is written like that currently.

**Comment by ebocher** [comment]
What about  if we consider that a selection is not available when the table does not contain a pk ?

**Comment by ebocher** [comment]
So what is the best option ?

**Comment by SPalominos** [comment]
A proposition :

- If there is n primary key : alert the user that some information will be lost, like the current selection, and do the sort directly server-side with adding `ORDER BY column ASC/DESC` and reopen the RowSet used to get the data to displayed in the JTable.
- If there is a primary key : when the table is displayed without any sort, a sort will be done on the primary key field which will give the basic rowId order. Then when a sort is done, do it server side and the the primary key field will allow to like the old rowId order with the new one like it is done actually.

**Comment by ebocher** [comment]
Sounds good for me
@nicolas-f

**Comment by nicolas-f** [comment]
Currently the underlying RowModel is always sorted by the primary key and take track of primary key blocks in order to skip region of table fast enough. This thing work only if the column value is unique. So it will not work at all if other non-unique columns is used.
 
Primary key are unique but almost never contiguous so you cannot use it as a row id.

**Comment by ebocher** [comment]
clap clap to @SPalominos
